### PR TITLE
Add the runValidators option to findOneAndUpdate call.

### PR DESCRIPTION
**Pull request by redwood-egarcea**
To support field validation on atomic updates without performing a non-atomic find and save.

### CODE REVIEW

**Comment by Zertz** [comment]
You can also do this from your schema.

```javascript
ClientSchema.pre('findOneAndUpdate', function (next) {
  this.options.runValidators = true
  next()
})
```

**Comment by redwood-egarcea** [comment]
Is adding a pre findOneAndUpdate hook preferable to performing validation on every findOneAndUpdate call? My expectation was for validation to occur on create or modify as default.

**Comment by Zertz** [comment]
This is something that was introduced in mongoose 4 and I haven't used it just yet. It can default to `false` with an option to enable it otherwise it's a breaking change.

Take a look at the defaults object: https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L37

You can add runValidators and use the options object in queries rather than hard-coding `true`.

**Comment by Zertz** [comment]
@florianholzapfel I think this lib already does quite a bit, since this is something that can be added easily to the schema, it may be best to leave it out?

**Comment by florianholzapfel** [comment]
although you can do this via the schema pre-hook, i think it is more convenient for the user to have it directly inside this lib, but it should be configurable.

**Comment by florianholzapfel** [comment]
you can configure it through the ```runValidators``` option. default is ```false```.

**Pull request merged**
