### PR TITLE
add option to set readPreference on request

### PR DESCRIPTION
**Pull request by mattcasey**
I wasn't able to run tests, but hopefully this works! :)

(I tried running `npm install` but when I tried to run the test, it complained "Cannot find module 'generate-object-property' ")

### CODE REVIEW

**Comment by Zertz** [comment]
Awesome, thanks! I'll take a look at the test and see what's going on.

`npm install` should work, which version of npm are you on?

**Comment by Zertz** [comment]
@mattcasey You forgot to call `done()` which is causing the test to timeout. This is a case where unit testing would be far more appropriate, but we're a bit lacking in that department so that test will do for now, even though there isn't really anything to assert.

What happens when you pass an invalid read preference, is it silently ignored or does it cause an error? Either way, it would be wise to add a test for that, just to be safe in case that behavior ever changes.

Also, please add `.read()` in **filterAndFindById.js** as well. This one isn't in 1.x which is probably why you missed it :smile:

**Comment by Zertz** [comment]
@mattcasey [Squash](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) these commits and we should be good to go!

**Comment by Zertz** [comment]
@florianholzapfel do you mind meeting this as-is?

**Comment by florianholzapfel** [comment]
perfect. thank you!

**Pull request merged**
