### PR TITLE
validate HTTP Status Code

### PR DESCRIPTION
**Pull request by danieljoppi**
HTTP Status Code: http://www.restapitutorial.com/httpstatuscodes.html
POST -> 201 - Created
PUT -> 200 - OK
DELETE -> 204 - No Content
GET -> 200 - OK

### CODE REVIEW

**Comment by florianholzapfel** [comment]
thank you!

**Comment by Yogu** [comment]
I'm a bit late to the party, but do you really think returning 404 for empty lists is a good idea? If you have a `customers` database, and it is initially empty, `GET /customers` will return 404 at the moment. I think it would be better to return `200` in this case because it is a perfectly fine request, and most definitely not a *client error*. If you agree, I'll create a pull request.

**Comment by romanmt** [comment]
I agree with Jan. I wouldn't want to have error handling in my code for an empty list. 




If an empty list is in fact an error condition for your application, then that is application specific logic that doesn't belong in this library. 



—

**Comment by florianholzapfel** [comment]
yes, you are right. an empty list should not lead to an error.

@Yogu i would appreciate your pull request very much

**Pull request merged**
