### PR TITLE
Disabling query limit when performing a 'distinct' action. Fixes #222

### LINKED ISSUE #222: distinct can't be use with server limit option
Steps to reproduce:

1. initialize restify with `limit: 20`
1. do a `distinct` query 

An error is thrown: `Error: limit cannot be used with distinct`

This acts the same as doing a `distinct=name&limit=20` query but these 2 situations are notably different. The server option limit should not apply to `distinct` queries

### PR DESCRIPTION
**Pull request by smirea**

### CODE REVIEW

**Comment by Zertz** [comment]
Looks good. @florianholzapfel ?

**Comment by florianholzapfel** [comment]
for me too.

**Comment by florianholzapfel** [comment]
thank you!

**Comment by smirea** [comment]
no sweat! when do you guys expect to publish this?

**Comment by Zertz** [comment]
I just published 2.4.2

**Comment by smirea** [comment]
awesome, thanks!

**Pull request merged**
