### PR TITLE
2.0.0: major refactoring and breaking improvements

### PR DESCRIPTION
**Pull request by Zertz**
**Don't merge anything yet!**

The primary goal was to make the code easier to read and maintain so I split `express-restify-mongoose.js` into modules. I've also refactored most (all?) anonymous functions to make it possible to write unit tests. It should also help with fixing some long standing issues.

[Here's the list of breaking changes](https://github.com/florianholzapfel/express-restify-mongoose/blob/refactor-anon-functions/CHANGELOG.md)

~~**Error handling**~~

~~Ugh, yes, this again. I've refactored it in a way that is still backward compatible for now. Basically, rather than pass around the `onError` function, code now calls `next(err)` and the lib ends with `app.use(onError)`.~~

~~This puts `onError` in a position where it could be completely removed which would let users use their own error middleware within their Express app. This is a point that came up in a issue that I can't seem to find at the moment.~~

### CODE REVIEW

**Comment by Zertz** [comment]
This is odd, tests are passing locally. I'll take a closer look later

**Comment by Zertz** [comment]
restify maintainers are working [on a PR](https://github.com/restify/node-restify/pull/892) that would allow using `next(err)` like express. e79a2a18130eb157aa63658459e1d1483a0f2b4d implements it. Depending on their timing, the change to error handling could wait for another release, especially since it doesn't have to be breaking.

I've also taken the liberty to implement what's discussed in issue #155, but obviously this is up for discussion.

This PR would be for 2.0.0

**Comment by Zertz** [comment]
@florianholzapfel Quick question for you. Do you know why some calls to `filter.filterObject` are wrapped in a try/catch block? I'm not at all familiar with what's going in **resource_filter.js**!

For example: https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/express-restify-mongoose.js#L608

**Comment by florianholzapfel** [comment]
actually, i don't remember anymore. i tried to have a quick look at the git history. it may be, that this try/catch block is just quick fix to work around some other problem?

**Comment by Zertz** [comment]
Alright, thanks for looking into it. I'll write some tests to try and see if it's possible to trigger an exception in there.

If you have some time to take a look at the changelog, I'd appreciate your input!

The remaining failing tests have to do with restify and error handling. I think I will rollback these changes to avoid forcing users into upgrading to the next major release of restify, which brings its own set of changes.

By the way, I'm @Zertz on Twitter if you want to DM me instead!

**Comment by Zertz** [comment]
Yay, got the tests passing again! Basically, I moved and removed a whole bunch of things.

This is the new flow for users: `preMiddleware` > `access` > query > `postMiddleware` > `outputFn`

I need to review the code again, but I think this is the complete list of **breaking changes**: I'm planning to put together some guidelines for upgrading.

* `options.private` and `options.protected` no longer accept comma separated fields, pass an array instead
* removed `options.excluded`, use `options.private`
* removed support for querying with parameters, use `url?query={"name":"hello"}`
* removed $and and $or passed as parameters, use `url?query={"$or":[...]}`
* removed `prereq`, use `preMiddleware` as a drop in replacement
* removed `postCreate`, `postUpdate`, and `postDelete`, use `postMiddleware`
* removed `postProcess`, use `postMiddleware` or override `outputFn`

This PR closes #155, #157 and #158 and makes fixing a few other issues easier than it was before.

There is still room for refactoring, but I'm quite happy with the feature set for now. I really want to write unit tests to complete those integration tests before merging anything though.

**Comment by Zertz** [comment]
@florianholzapfel I am normalizing `populate` internally to always use the full blown mongoose implementation. This remains backward compatible and fixes nested populates (yay!)

```javascript
model.populate([{
  path: 'foo',
  select: 'bar'
}])
```

Now the interesting part is that this has accidently led me into some dark corners of the resource filter and caused it to throw an exception [here](https://github.com/florianholzapfel/express-restify-mongoose/blob/master/lib/resource_filter.js#L116), which would explain the try/catch blocks. The underlying cause simply seems to be that `opts.populate` isn't always set so `opts.populate.split(',')` crashes.

**Comment by Zertz** [comment]
@florianholzapfel I'm going to confirm this is also broken in master, but if so 241fae5 and 3d6ef85 contain a security fix that should be backported to v1. In some cases, queries with protected or public access can remove private fields from a document.

Tests to reproduce: [private](https://github.com/florianholzapfel/express-restify-mongoose/blob/refactor-anon-functions/test/integration/access.js#L158), [protected](https://github.com/florianholzapfel/express-restify-mongoose/blob/refactor-anon-functions/test/integration/access.js#L326), [public](https://github.com/florianholzapfel/express-restify-mongoose/blob/refactor-anon-functions/test/integration/access.js#L488)

By the way, the massive amount of added lines are tests (more to come!). The code itself has actually shrunk.

**Comment by Zertz** [comment]
@florianholzapfel Alright, everything's looking good on my end! Just docs left to update, I'll get this done very soon.

Feel free to merge, tag and publish as 2.0.0

**Comment by florianholzapfel** [comment]
great work!

**Pull request merged**
