### PR TITLE
Handle errors from filterObject() and use next(err) for express

### PR DESCRIPTION
**Pull request by 09setht**

### CODE REVIEW

**Comment by Zertz** [comment]
next(err) is no longer necessary since you can simply implement a custom onError handler (which could itself call `next(err)`)

Not sure about the other commit because of the formatting.

**Comment by syzer** [comment]
the problem with handler is that you loose encapsulation.

**Comment by Zertz** [comment]
@syzer What doi you mean exactly by losing encapsulation?

**Comment by syzer** [comment]
1. next():
if A calls B:
A->B
A is dependent on B:
A(B)

2:
if A emits event (error),
that is caught by B
A is also dependent on B
but in this case this dependency is non explicit.

**Comment by Zertz** [comment]
@syzer Alright, I understand your point. Keep in mind that onError was rewrote to maintain backward compatibility so that's the best that could done at the time.

If you take a look here: https://github.com/florianholzapfel/express-restify-mongoose/blob/1.0.0-dev/lib/express-restify-mongoose.js#L165

We could simply to replace `res.status(err.status).send(errorString);` by `next(err)`. The drawback is that the lib loses some simplicity since there no longer is a default to handle errors, which I think is a dealbreaker.

It could be used behind something like `options.useNextError` (yes, that's a terrible name). Feel free to share your ideas!

**Pull request closed without merging**
