### PR TITLE
Updated readme to use Express4 Router

### PR DESCRIPTION
**Pull request by Zertz**
When using Express4, it is good practice not to pass the whole app, but instead simply pass the router.

### CODE REVIEW

**Comment by florianholzapfel** [comment]
thank you!

**Comment by Zertz** [comment]
@florianholzapfel I created a wiki page to extend the options with some examples. Very much a WIP at the moment, but I think it will be helpful as trying to stick everything in the readme gets unwieldly.

**Comment by florianholzapfel** [comment]
i appreciate that. thank you very much for your efforts!

**Comment by Zertz** [comment]
No problem, this project has been very helpful to me! I'll put some more effort into it and put together more examples as I feel this is what is the most helpful for the community.

I also have a couple features in mind so I'll try to dive into the code sometimes. Ugh, days are too short!

**Pull request merged**
