### PR TITLE
handle filtering of nested, populated and discriminator fields

### PR DESCRIPTION
**Pull request by Zertz**
Added tests for filtering:

- Arrays of populated documents
- Nested populated documents
- Populated document in a discriminator

Improved:
- Use lodash rather than custom functions whenever possible
- Handle null middleware

### CODE REVIEW

**Comment by Zertz** [comment]
@florianholzapfel I'm going to merge this and tag as 2.3.0-beta.1

**Don't use this in production unless you have very extensive tests in place**

**Comment by Zertz** [comment]
@dvlsg I merged your PR in this branch which is on npm now as **2.3.0-rc.1**.

We now have rather extensive test coverage, but if you have your own API tests, please run them against this version and keep us posted!

**Comment by dvlsg** [comment]
Great, thanks! Working on pulling down that version so we can push to our staging environment for a proper test. Will post an update when we put it through our paces.

**Comment by dvlsg** [comment]
:+1: All good on our end! The original issue we were having has been resolved when using **2.3.0-rc.1**.

**Comment by Zertz** [comment]
Alright, good to hear! I'm wrapping up a few things on my end, but I haven't stumbled on anything so far either. Unless something comes up, 2.3 should be out tomorrow.

**Pull request merged**
