### PR TITLE
Modifications for custom remove command for soft-deletes

### PR DESCRIPTION
**Pull request by robinduckett**
May be controversial, but as "remove" is hard coded, and three attempts to implement soft deleting into mongoose whilst using this module have failed, I propose the ability to modify the "remove" method, so it can be replaced with your own Mongoose method, such as "delete" or k-mongoose-soft-delete's "softDelete".

No need to merge if there is a better proposed way of doing this, and maybe this will save someone two days of pointless work, as it would have done for myself.

### CODE REVIEW

**Comment by Zertz** [comment]
There's an example in preRemove in the docs. Does that help you?

**Comment by robinduckett** [comment]
The preDelete example in the docs does not allow for continuing the middleware chain, so for example, if you have a postDelete, it never fires.

**Comment by robinduckett** [comment]
As it happens, in practice, this code is all wrong. For some reason you can't access the methods that any plugin is providing.

**Comment by Zertz** [comment]
Oh I see. Since you are soft deleting, is it possible for you to move your postDelete logic earlier?

I understand the use-case, but I'm not sure whether we need to add a layer of complexity here.

**Pull request closed without merging**
