### PR TITLE
chore(deps): bump mongoose to ~4.0.0

### PR DESCRIPTION
**Pull request by Zertz**
- Introduces many breaking changes, lib needs updates

### CODE REVIEW

**Comment by Zertz** [comment]
Don't merge this just yet, it's broken in many ways at the moment!

**Comment by Zertz** [comment]
@florianholzapfel There!

I've also added a changelog with the breaking changes which are:

-
> **This release is no longer compatible with mongoose 3**

* updated mongoose to version 4
* removed fullErrors, implement a custom onError handler instead

-

I've also taken the liberty to refactor how defaults are set. It now relies on lodash instead which should be more reliable than the look that was used before.

**Comment by florianholzapfel** [comment]
@Zertz thank you very much for this pr. you are awesome!

**Comment by Zertz** [comment]
@florianholzapfel I've noticed a few *TODO's* in your code:

1. https://github.com/florianholzapfel/express-restify-mongoose/blob/1.0.0-dev/lib/express-restify-mongoose.js#L663
2. https://github.com/florianholzapfel/express-restify-mongoose/blob/1.0.0-dev/lib/express-restify-mongoose.js#L715

These two are related to `options.strict` which states:
> When set to true, disallows DELETE all, POST with id param, and PUT without id param

- *DELETE all* should be removed, unless there really is use-case where removing every single document from an API is both useful and **safe**
- *POST with id param* is fine and possibly shouldn't even be flagged behind strict
- *PUT without id param* doesn't make sense since PUT is meant for known resources

**What I'm getting to is: is `options.strict` even necessary?**

-

3. https://github.com/florianholzapfel/express-restify-mongoose/blob/1.0.0-dev/lib/express-restify-mongoose.js#L262
4. https://github.com/florianholzapfel/express-restify-mongoose/blob/1.0.0-dev/lib/express-restify-mongoose.js#L327

I haven't really looked deep into these two. The former could be deprecated, but removing it entirely would be a huge breaking change I believe. The latter mostly looks like a refactor/feature, which can wait.

-

I've also gone through issues and there doesn't seem to be anything in there that would introduce more breaking changes. Could you confirm?

I'll tackle #72 sometimes in the future, I think it's a useful feature and definitely one I'd use. Other than that, quite a few issues (#112, #109, #81, #78, #52 and #51) seem to be at least vaguely related, but non-breaking.

**Pull request merged**
