### PR TITLE
feat: option to include total count header

### PR DESCRIPTION
**Pull request by Zertz**
See issue #141

- [x] Support for GET /Model

### CODE REVIEW

**Comment by Zertz** [comment]
@florianholzapfel Can you have a quick look at this?

**Example 1**

```js
erm.serve(router, Model, {
  totalCountHeader: true
})
```

Response to `GET /Model`
```
Headers: {
  'X-Total-Count': 5
}
```

**Example 2**

```js
erm.serve(router, Model, {
  totalCountHeader: 'X-Custom-Count'
})
```

Response to `GET /Model`
```
Headers: {
  'X-Custom-Count': 5
}
```

**Comment by florianholzapfel** [comment]
I like the second example more as it seems more flexible

**Comment by Zertz** [comment]
Both work actually :)

**Comment by florianholzapfel** [comment]
I have not realized that both work.

**Comment by Zertz** [comment]
Thanks! Published as 2.4 and updated docs

**Pull request merged**
