### PR TITLE
refactor(filter): decouple from lib

### PR DESCRIPTION
**Pull request by Zertz**
Filters are now stored in the core module, which will eventually allow the resource filter to be removed from core.

I have also cleaned up the interface and the functions themselves are loosely coupled, so it is now possible to split them into different modules.

Finally, the constructor is now "pure", as it no longer mutates its parameters.

As a bonus, filtering now happens right before output, allowing access to the full document within post middleware and closing #186. This could possibly be a breaking change for some users.

*Known issues*

- [x] PR #216 needs to be merged
- [x] Filtering populated models is broken
- [x] Unit tests are broken
- [x] Merge PR #218 
- [x] Merge PR #221

### CODE REVIEW

**Comment by Zertz** [comment]
@florianholzapfel Can you have a look at this? This is mostly paving the way for further improving the filter.

**Comment by florianholzapfel** [comment]
@Zertz looks good to me

**Comment by Zertz** [comment]
Cool! Might be nice to implement @smirea's idea in #224 at the same time since both might be a breaking change for some users.

**Comment by Zertz** [comment]
Alright, I extracted `removeValueAtPath` and `getModelAtPath` from the filter and moved them into their own repositories: [weedout](https://github.com/Zertz/weedout) and [mongoose-detective](https://github.com/Zertz/mongoose-detective). @florianholzapfel Feel free to have another look and merge!

**Comment by florianholzapfel** [comment]
great work!

**Pull request merged**
